FROM arm32v7/ubuntu:rolling

# Global environment settings
ENV DEBIAN_FRONTEND=noninteractive

# Configure
WORKDIR /etc/

EXPOSE 443

# Install
RUN apt-get update && apt-get install -y --no-install-recommends \
    wget curl net-tools bind9-dnsutils iputils-ping tzdata lighttpd lighttpd-mod-openssl && \
# Cleaning up
    apt-get autoremove -y --purge && \
    rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["lighttpd", "-D", "-f", "/etc/lighttpd/lighttpd.conf"]

