FROM arm64v8/ubuntu:22.04

LABEL maintainer="BOINC" \
      description="A lightweight BOINC client on ARMv8 64-bit architecture."

# Global environment settings
ENV DEBIAN_FRONTEND=noninteractive

# Copy files
ADD start-gridcoin.sh /usr/local/bin
RUN chmod 755 /usr/local/bin/start-gridcoin.sh

# Install
RUN apt-get update && apt-get install -y --no-install-recommends \
# Install Time Zone Database
    tzdata ca-certificates gpg-agent \
# Install PPA dependency
    software-properties-common && \
# Install GridcoinResearchd
    add-apt-repository -y ppa:gridcoin/gridcoin-stable && \
    apt-get update && apt-get install -y --no-install-recommends \
    gridcoinresearchd && \
    groupadd -g 1000 me && \
    useradd -g 1000 -m -s /bin/bash me && \
# Cleaning up
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /home/me

CMD ["/usr/local/bin/start-gridcoin.sh"]

